"use client";

import Link from "next/link";
import Footer from "../../../components/layout/Footer";

const sections = [
  {
    title: "1. Overview",
    body: `RomanceCanvas is an AI-powered interactive fiction and storytelling platform operated by AIRomanceBuilder Labs. By creating an account or purchasing a subscription, you agree to these Terms of Service and confirm that you are at least 18 years of age.`,
  },
  {
    title: "2. Service Description",
    body: `We provide an interactive fiction platform where users can create and experience AI-generated stories across various genres including romance, fantasy, science fiction, and more. Our service includes text-based conversations with AI characters and AI-generated illustrations to enhance the storytelling experience.`,
  },
  {
    title: "3. Content Nature and Maturity Settings",
    body: `RomanceCanvas does not host, distribute, or promote pornographic or explicit sexual content. Our platform offers creative storytelling with optional mature themes at users' discretion, including romantic scenarios, emotional depth, and adult-oriented narrative content. Users may adjust content maturity settings ("Creative Freedom Mode" or "Mature Content") to enable or disable filters during creative sessions. All content is AI-generated fiction for entertainment and artistic purposes. We maintain strict content policies prohibiting illegal content, exploitation, or materials depicting minors in any context. Content moderation systems help ensure compliance with our Acceptable Use Policy and applicable laws.`,
  },
  {
    title: "4. Eligibility & Age Verification",
    body: `You must be 18 years of age or older to use RomanceCanvas. By using our service, you represent and warrant that you are of legal age in your jurisdiction. We reserve the right to request age verification at any time. Keep your login credentials private and notify us immediately if you suspect unauthorized access.`,
  },
  {
    title: "5. Subscriptions & Billing",
    body: `All paid plans operate on a subscription basis with recurring billing. Payment processing is handled securely through our third-party payment processors. Your subscription will renew automatically until cancelled. You may cancel at any time from your account dashboard; access continues until the end of the current billing period. All prices are in USD unless otherwise stated.`,
  },
  {
    title: "6. Acceptable Use Policy",
    body: `You agree to use RomanceCanvas only for lawful purposes and in accordance with these Terms. Prohibited activities include: (a) generating content depicting illegal activities, (b) creating content involving minors in any context, (c) attempting to bypass content filters or security measures, (d) harassing or threatening others, (e) violating intellectual property rights, (f) using the service for unauthorized commercial purposes. We reserve the right to suspend or terminate accounts that violate these rules without refund.`,
  },
  {
    title: "7. Content and Intellectual Property",
    body: `All software, AI models, branding, and platform assets remain the exclusive property of AIRomanceBuilder Labs. You retain ownership rights to the original prompts and inputs you provide. AI-generated stories and images are licensed to you for personal, non-commercial use. You may download and save your stories for personal use but may not redistribute, sell, or use them for commercial purposes without prior written consent.`,
  },
  {
    title: "8. AI-Generated Content Disclaimer",
    body: `All content generated by our AI is fictional and for entertainment purposes only. AI-generated characters, scenarios, and narratives are entirely fictional and do not represent real people or events. We do not guarantee accuracy, appropriateness, or quality of AI-generated content. Users are responsible for reviewing AI-generated content before use.`,
  },
  {
    title: "9. User Responsibilities",
    body: `You are responsible for: (a) maintaining the confidentiality of your account, (b) all activities that occur under your account, (c) ensuring your use complies with applicable laws, (d) understanding that AI-generated content is fictional entertainment. You agree to immediately notify us of any unauthorized use of your account.`,
  },
  {
    title: "10. Content Moderation",
    body: `We employ automated and manual content moderation systems to ensure compliance with our policies and applicable laws. We reserve the right to review, monitor, edit, or remove any content at our discretion. Some content may be subject to additional review or restrictions based on content maturity settings.`,
  },
  {
    title: "11. Refunds and Cancellation",
    body: `All purchases are final and non-refundable. We do not accept returns or provide refunds for subscriptions, credits, or digital goods, except where required by law. You may cancel your subscription at any time; cancellation stops future billing but does not refund prior charges or partially used periods. If you believe you were charged in error (e.g., duplicate charge), contact support within 7 days and we will review and correct any confirmed mistakes.`,
  },
  {
    title: "12. Service Modifications",
    body: `We reserve the right to modify, suspend, or discontinue any aspect of the service at any time. We will provide reasonable notice of material changes to paid subscribers. Continued use of the service after changes constitutes acceptance of modified terms.`,
  },
  {
    title: "13. Limitation of Liability",
    body: `RomanceCanvas is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, consequential, or punitive damages arising from your use of the service. Our total liability shall not exceed the amount you paid for the service in the 12 months preceding any claim.`,
  },
  {
    title: "14. Privacy and Data Protection",
    body: `Your privacy is important to us. We collect and process personal data in accordance with our Privacy Policy. We use industry-standard security measures to protect your data. For complete details, please review our Privacy Policy.`,
  },
  {
    title: "15. Third-Party Services",
    body: `Our service integrates with third-party payment processors, AI providers, and other services. Your use of these third-party services is subject to their respective terms and conditions. We are not responsible for third-party services or their practices.`,
  },
  {
    title: "16. Dispute Resolution",
    body: `Any disputes arising from these Terms or your use of the service will be resolved through good faith negotiation. If negotiation fails, disputes will be subject to binding arbitration in accordance with applicable arbitration rules.`,
  },
  {
    title: "17. Governing Law",
    body: `These Terms are governed by and construed in accordance with applicable international commerce laws. You agree to submit to the jurisdiction of courts for resolution of any disputes not subject to arbitration.`,
  },
  {
    title: "18. Changes to Terms",
    body: `We may update these Terms to reflect new features, legal requirements, or operational changes. Material changes will be communicated via email or in-app notification at least 30 days before taking effect. Continued use of the service after changes constitutes acceptance.`,
  },
  {
    title: "19. Contact Information",
    body: `For questions about these Terms, please contact us at support@romancecanvas.com. For technical support, email support@romancecanvas.com. We aim to respond within 24-48 business hours.`,
  },
  {
    title: "20. Severability",
    body: `If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary while the remainder of these Terms will remain in full force and effect.`,
  },
  {
    title: "21. Entire Agreement",
    body: `These Terms, together with our Privacy Policy and Refund Policy, constitute the entire agreement between you and AIRomanceBuilder Labs regarding the use of RomanceCanvas and supersede all prior agreements and understandings.`,
  },
];

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-purple-900 via-indigo-900 to-slate-900 text-white">
      <section className="max-w-4xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="inline-flex items-center text-sm text-purple-200 hover:text-pink-200"
        >
          Back to RomanceCanvas
        </Link>
        <h1 className="mt-6 text-4xl font-black tracking-tight">
          RomanceCanvas Terms of Service
        </h1>
        <p className="mt-4 text-base text-purple-100">
          Last updated: {new Date().toLocaleDateString()}
        </p>

        <div className="mt-12 space-y-10">
          {sections.map(({ title, body }) => (
            <article
              key={title}
              className="bg-white/5 rounded-3xl p-6 border border-white/10 shadow-lg shadow-purple-500/10"
            >
              <h2 className="text-2xl font-semibold text-pink-200">{title}</h2>
              <p className="mt-3 text-sm leading-relaxed text-purple-50">
                {body}
              </p>
            </article>
          ))}
        </div>

        <div className="mt-12 text-sm text-purple-200">
          These Terms apply together with our{" "}
          <Link href="/legal/privacy" className="underline hover:text-pink-200">
            Privacy Policy
          </Link>{" "}
          and{" "}
          <Link href="/legal/refund" className="underline hover:text-pink-200">
            Refund Policy
          </Link>
          .
        </div>
      </section>

      <Footer />
    </main>
  );
}
